import type { APIDay } from "./day.types";
import type { Location } from "./player.types";
import type { APIExerciseSet } from "./workout.types";

export interface APISportActivityPain {
  id: number;
  rating: number;
  location: Location;
  locationId: number;
  sportActivityId: number;
  dateUpdated: string | null;
}

export interface APISportActivity {
  id: number;
  dataSource: string | null;
  distance: number | null;
  speed: string | null;
  duration: number | null;
  elevation: number | null;
  power: number | null;
  averagedBpm: number | null;
  rpe: number | null;
  fitnessLevel: number | null;
  cardioRespiratory: number | null;
  muscularDifficulty: number | null;
  timeOfActivity: string | null;
  dateAdded: string | null;
  activityTypeId: number | null;
  athleteDayId: number;
  fatigueLevel: number | null;
  pleasureLevel: number | null;
  activeCalories: number | null;
  deviceName: string | null;
  cadence: number | null;
  elevationDescent: number | null;
  dateUpdated: string;
  hasChanged: boolean | null;
  trainingLoad: number | null;
  gameActivity: boolean | null;
  strain: number | null;
  distance07Kmh: number | null;
  distance714Kmh: number | null;
  distance1419Kmh: number | null;
  distance1925Kmh: number | null;
  distance25PlusKmh: number | null;
  nbEffortsAbove198Kmh: number | null;
  nbEffortsAbove25Kmh: number | null;
  topSpeed: number | null;
  eventType: string | null;
  vmaxAcceleration: number | null;
  vmaxDeceleration: number | null;
  nbDecelerationsAbove3ms2: number | null;
  nbAccelerationsAbove3ms2: number | null;
  energyConsumptionCarbs: number | null;
  energyConsumptionFats: number | null;
  epocFinal: number | null;
  epocPeak: number | null;
  hfAverage: number | null;
  lfAverage: number | null;
  lfHfRatio: number | null;
  rmssd: number | null;
  trimp: number | null;
  zone1Time: number | null;
  zone2Time: number | null;
  zone3Time: number | null;
  zone4Time: number | null;
  zone5Time: number | null;
  energyConsumptionSeries: string | null;
  epocSeries: string | null;
  heartRateSeries: string | null;
  trimpSeries: string | null;
  movementLoad: number | null;
  fcMax: number | null;
  workoutSessionInstanceId: number | null;
  athleteDay: APIDay;
  sportActivityPains: APISportActivityPain[];
  exerciseSets: APIExerciseSet[];
}
